x-defaults: &app-image
  build: ./.docker
  image: pastvu_node
  environment:
    - NODE_ENV=development
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:

  httpBackend:
    image: nginx
    volumes:
      - store:/usr/share/nginx/html
    ports:
      - "127.0.0.1:8081:80"

  fileserver:
    build: fileserver
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - store:/store

  mongo:
    image: mongo:4.4
    volumes:
      - ./pastvu.gz:/pastvu.gz
      - mongo4:/data/db
      - ./.docker/dev-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "127.0.0.1:27017:27017"

  redis:
    image: redis:6.2.6
    ports:
      - "0.0.0.0:6379:6379"

  app:
    << : *app-image
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - store:/store
    command: run app --primary
    depends_on:
      - "mongo"
      - "redis"

  worker:
    << : *app-image
    volumes:
      - .:/code
      - store:/store
    command: run worker
    depends_on:
      - "app"

  notifier:
    << : *app-image
    volumes:
      - .:/code
    command: run notifier
    depends_on:
      - "app"

  uploader:
    << : *app-image
    volumes:
      - .:/code
      - store:/store
    command: run uploader
    depends_on:
      - "app"

  downloader:
    << : *app-image
    volumes:
      - .:/code
      - store:/store:ro
    command: run downloader
    depends_on:
      - "app"

  sitemap:
    << : *app-image
    volumes:
      - .:/code
      - sitemap:/sitemap
    command: run sitemap
    depends_on:
      - "app"

  mailpit:
    image: axllent/mailpit:latest
    ports:
     - "127.0.0.1:1080:8025"

volumes:
  store:
  sitemap:
  mongo4: